baseURL = 'http://example.org/'
title        = "sandra romero pinto"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "phd candidate - harvard university"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    
    [languages.en.params.logo]
      logoText = "hello!"
      logoHomeLink = "/"
    # or
    #
    #  path = "/img/punta_roquitas_romero.jpeg"
    #  alt = "Your example logo alt text"

  # And you can even create generic menu
  
[[menu.main]]
    identifier = "publications"
    name       = "publications"
    url        = "/publications"

[[menu.main]]
    identifier = "blog"
    name       = "blog"
    url        = "/posts"
